### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by ajthinking** [data-story-org/discuss#1]
# Discussion

DataStory provides a workbench for designing data flow diagrams.

![image](https://user-images.githubusercontent.com/3457668/117117786-3d48a900-ad90-11eb-91eb-520f7919d7fa.png)

### DataStory name change
The organisation name 'data-story' is already taken on github. :worried:

I could keep my product name anyways and simply name my organisation 'data-story-org'. That would giving repo urls such
```
data-story-org/core
data-story-org/server
data-story-org/gui
```

Or, I can reuse the name pipe-dream which I already own but which content have been deprecated.

That would give repo urls like this:
```
pipe-dream/core
pipe-dream/server
pipe-dream/gui
```

A third way is to consider data-story a product <i>within</i> pipe-dream and thus combine both names. This would allow repos to live within pipe-dream but I can still refer to it as data-story.

![image](https://user-images.githubusercontent.com/3457668/124446600-dc822080-dd80-11eb-8c2e-d7a077b67f71.png)

### Questions
* Which name/name combination fits the best?
* Any ideas for other names?
* Potential headache reusing an old name to a new product?
* Any other thoughts

**Comment by ajthinking** [comment]
@NickeGilbert @brainmaniac can you help me with your thoughts?

**Comment by brainmaniac** [comment]
Hello A-dawg!

Hmmm. this is a hard one and I think that the first question you probably have to answer on your own:
_Can data-story be named something else or is it's name data-story?_

If you feel that it's name is data-story then first step I'd do is to maybe contact github or something to see if there is any way you can get in touch with the current owner. The org seems unused. I paid 1000 kr for facebook.com/pimpmydrawing

If that doesn't work I guess you have to do the **data-story-org** until you earn enough money to convince them to sell the name..

If you can live with a name change PipeDream is probably as good as any 🤷 , no?
If you go down that path you probably should zip all your Pipdream code and save in some deep dungeon somewhere but then wipe everything from your computer and current repo to not mix stuff up. 

I think in a way that naming reveals how well defined the stuff you are doing is. I think that this, data-story or whatever name it will end up with, is very cool, fantastic and interesting 🤩  but it is also aiming on doing a lot of different things. The scope is IMENSE.. and I know that the whole idea is that it **_should_** be able to do anything. And once it is there that will be AMAZING.. but until then I don't know what path is best. One need to consider the elevator pitch. With that in mind I am not a huge fan of data-story becoming a subproject to PipeDream. It seems to me as if that is complicating stuff just because someone took data-story as an organisation name on github.

I think considering the ease of structure I'd recommend something like:

**github.com/data-story-org/data-story**

- Here you have the data story repo


**github.com/cool-use-case-product/cool-use-case-product**

- You make a new organisation when you make specific products. These have **data-story-org/data-story** as a dependency but for now are not part of that org to KIS.

I don't know if this helps you at all but it was my spontaneous rambling 😅
